
/**
 * This file was generated by TONDev.
 * TONDev is a part of TON OS (see http://ton.dev).
 */
pragma ton-solidity >= 0.35.0;
pragma AbiHeader expire;
pragma AbiHeader pubkey;
import "./Pair.sol";

// This is class that describes you smart contract.
contract NFTAuction is Pair {
    NFTPairTypes public type_contract = NFTPairTypes.CrystallAuction;
    uint128 public step;
    constructor (uint128 _price, uint64 _time, address _seller, uint256 _seller_pubkey, uint128 _commission, uint128 _step) public {
        require(tvm.pubkey() != 0, 101);
        require(msg.pubkey() == tvm.pubkey(), 102);
        seller = _seller;
        seller_pubkey = _seller_pubkey;
        receiver = _seller;
        receiver_pubkey = _seller_pubkey;
        price = _price;
        finish_time = _time;
        seller = _seller;
        commission = _commission;
        step = _step;
    }

    function getBet(uint256 pubkey) public onlyOpen onlyInTime{
        require(msg.value >= price,YOU_ARE_NOT_GOD);
        tvm.commit();
        if (seller != receiver) {receiver.transfer(price - step,false,0);}
        receiver = msg.sender;
        receiver_pubkey = pubkey;
        price = msg.value + step;

    }



}
