
/**
 * This file was generated by TONDev.
 * TONDev is a part of TON OS (see http://ton.dev).
 */
pragma ton-solidity >= 0.35.0;
pragma AbiHeader expire;
pragma AbiHeader pubkey;
import "./Pair.sol";


// This is class that describes you smart contract.
contract NFTPair is Pair {
    NFTPairTypes public type_contract = NFTPairTypes.CrystallPair;
    constructor (uint128 _price, uint64 _time, address _seller, uint256 _seller_pubkey, uint128 _commission) public {
        require(tvm.pubkey() != 0, 101);
        require(msg.pubkey() == tvm.pubkey(), 102);
        seller = _seller;
        seller_pubkey = _seller_pubkey;
        receiver = _seller;
        receiver_pubkey = _seller_pubkey;
        price = _price;
        finish_time = _time;
        seller = _seller;
        commission = _commission;
    }

    function sell(uint256 pubkey) public onlyOpen onlyInTime {
        require(msg.value >= price,NOT_ENOUGH_MONEY);
        require(pubkey != 0, 102);
        tvm.accept();
        tvm.log("accept");
        receiver = msg.sender;
        receiver_pubkey = pubkey;
        status = StatusPair.close;
        Pair.finish_tech();
    }


}
